### ISSUE TITLE
Allow for passing of a custom Lottie animation instead of hardcoding to fancy_checkmark.json

### ISSUE THREAD

**Issue by MalcolmMcFly** [quickbirdstudios/SurveyKit#13]

**Comment by MalcolmMcFly** [comment]
@KlausNie This is already implemented?

**Comment by KlausNie** [comment]
@MalcolmMcFly It is in this branch https://github.com/quickbirdstudios/SurveyKit/tree/feature/allow-custom-lottie-animation , currently in review

**Comment by KlausNie** [comment]
in 1.1.0
