### ISSUE TITLE
Step constructors....resource INTS or STRINGS? 

### ISSUE THREAD

**Issue by AnWaTr** [quickbirdstudios/SurveyKit#14]
Hello all!  This is a wonderful API and thank you for creating it. 

I've downloaded (via ZIP) the current code base for SurveyKit and am working through the process of making my own survey.  In the ZIPPED code, all of the Step derived classes seem to require String? objects.  For example:

open class InstructionStep(
    private val title: String? = null,
    private val text: String? = null,
    private val buttonText: String = "Start",
...
}

That is great!  However when I make a new project and bring in version 1.0.0 of SurveyKit:

    // Bring in the SurveyKit API
    // https://github.com/quickbirdstudios/SurveyKit
    implementation "com.quickbirdstudios:surveykit:0.1.0"

It appears all of the Step derived classes now want nullable Ints only? For example:

open class InstructionStep(
    @StringRes private val title: Int? = null,
    @StringRes private val text: Int? = null,
    @StringRes private val buttonText: Int = R.string.start,
...
}

For the app I am trying to design, I need to send in String objects directly as I am reading the survey data dynamically at runtime (from an Excel file) and won't have any known resource IDs. 

Is there an earlier version of SurveyKit I can pull down that still operates on String constructor parameters? 

Thanks for any guidance! 

Andrew

**Comment by AnWaTr** [comment]
Ah ha - I've found my own answer.  Looks like I was not referencing 1.0.0!  I've updated to the correct versions and constructors do indeed take strings. 

Thanks!

**Comment by KlausNie** [comment]
Yes that was a design flaw at the beginning. Happy that you could resolve it yourself!👍🏻
