### ISSUE TITLE
Setup instruction is out-dated

### ISSUE THREAD

**Issue by sarbyn** [quickbirdstudios/SurveyKit#21]
Change the example code from
```
<com.quickbirdstudios.survey_kit.public_api.survey.SurveyView
    android:id="@+id/survey_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```
To
```
<com.quickbirdstudios.surveykit.survey.SurveyView
    android:id="@+id/survey_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```
Otherwise a runtime error is thrown
`
[...]
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.quickbirdstudios.survey_kit.public_api.survey.SurveyView
[...]
`

**Comment by KlausNie** [comment]
Thank you very much for reporting this!

Adjusted ✅
