### ISSUE TITLE
Unable to change theme colour. 

### ISSUE THREAD

**Issue by VipinRewardz** [quickbirdstudios/SurveyKit#55]
The theme and text colour doesn't change even after changing the colours in configuration file.

**Comment by nikita-blizniuk** [comment]
I've got that issue too.
I suppose the problem is in InfoTextPart.kt file. `style` function is empty and don't change text colour.
Text colour is always set by `setTextColor(ContextCompat.getColor(context, R.color.survey_text))`.
But this is my guess :)

**Comment by VipinRewardz** [comment]
It was resolved. Sorry for all the troubles.
