### ISSUE TITLE
Use String instead of StringRes in Question Step

### ISSUE THREAD

**Issue by rahul260792** [quickbirdstudios/SurveyKit#8]
I am trying to set a string dynamically fetched from an API to the question but `QuestionStep` only allows `StringRes`. Any solution for that?

**Comment by sellmair** [comment]
We will make sure to support this in the next release. You can expect it within the next two weeks.

**Comment by KlausNie** [comment]
Is merged into develop. Will be in the next release.

**Comment by rahul260792** [comment]
Is this released in 1.0.0?

**Comment by sellmair** [comment]
Yes!
